twilio:
  account_sid: AC79b28632609dd6d4d30d7a2168c4a495
  auth_token: "replace with the new one!"
  number: +17012050594

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:superchatdb
    username: sa
    password:
    driverClassName: org.h2.Driver